version: "3.8"

services:
  app_test:
    container_name: test_api
    image: test_api
    command: "pytest ./tests"
    build:
      context: .
      dockerfile: Dockerfile-tests
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - database
    networks:
      - backend_network

  database:
    container_name: postgres_ctr
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network
    driver: bridge

volumes:
  postgres_data:
