version: "3.8"

services:
  app:
    container_name: squad_manager_api
    image: backend_api
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - database
    networks:
      - backend_network

  database:
    container_name: postgres_container
    image: postgres:12
    env_file:
      - .env
    ports:
      - "54322:5432"
    restart: always
    networks:
      - backend_network

  pg_admin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: always
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network
    driver: bridge
